### ISSUE TITLE
Make scrollController optional

### ISSUE THREAD

**Issue by LHARISMENDY** [FabioFiuza/scrollable_clean_calendar#39]
We use the calendar inside a sliding sheet with a jumpTo(offset) with the previous scrollController. It's generic to other components and we need to keep the scrollController. Is it possible to make it optional again ?

**Comment by rodrigodobbin** [comment]
Hi, it's possible for you to use the new methods (jumpToMonth ou ScrollToMonth) inside calendar Controller? 

Or in your project it's obligated to use offset instead of a "Date jump"?

But we'll look to it. Because we are using other package for the scrollController to our Date jump could work. And if we use the old scrollController we problably would have some functionalities that don't work together. for example JumpTo(offset) will use the old scrollController, and JumpToMonth will use the new one. And you problably couldn't use both, you will have to choose one.

So it will be better if you can use the new methods in your project, but we will look to it.

**Comment by rodrigodobbin** [comment]
I Just made a PR that will allow you to use again scrollController, but Remember:

**if you use this controller the Parameter `initialFocusDate` and the Functions `scrollToMonth` and `jumpToMonth` won't work since this override the scrollable controller. Do not use them together or you will receive a nullPointer Exception**

**Comment by rodrigodobbin** [comment]
@LHARISMENDY 

PR #41 is Done and the release 1.4.0 should fix it for you.

Please tell us if everything was okay.

Cya

**Comment by LHARISMENDY** [comment]
It works perfectly, thanks a lot for your answer and your PR !!
