### ISSUE TITLE
Start day of week

### ISSUE THREAD

**Issue by hurgoon** [FabioFiuza/scrollable_clean_calendar#8]
Thanks for the great library. 
When I change the 'startWeekDay' to DateTime.sunday, only Sunday date be shown, others invisible. 
I tried to change all days of the week as the start day, but only Monday is ok. 
I used the sample of this git(basic version).
If you need data or something from me, plz let me know.
Thanks in advance.

![Screen Shot 2021-06-04 at 3 03 50 PM](https://user-images.githubusercontent.com/42861952/120753443-2095c180-c546-11eb-916d-96775a210797.png)

**Comment by dobbinx3** [comment]
Thanks for using our widget. Hope you enjoying it. I'll try to take a look at it this next days. If I can't reproduce it, I'll be in touch.

Cya.

**Comment by hurgoon** [comment]
Sir, any update?

**Comment by hurgoon** [comment]
I edited the repo for the Sunday start calendar. 
Anyone who needs this version, use the following repo until Dobbinx3 made a proper upgrade.
https://github.com/hurgoon/scrollable_clean_calendar

**Comment by rodrigodobbin** [comment]
@hurgoon I just release a Major version (1.0.0) of this package. And this version fix this issue for you. Huge thanks to @EduardoNatale that work on this release.

If you want to update for this new version, please read the new Readme File because we made some considerable changes.

Thanks again for your collaboration. 

Cya.
